---
###############
# Rules by id #
###############
MD003: false                  # Heading style
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 120            # Line length 120 is far to short
MD014: false                  # Dollar signs without showing output
MD026:
  punctuation: ".,;:!。，；:"   # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading
MD041: false                  # First line in file should be a top level heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
